services:
  web:
    image: ${WEB_IMAGE:-saldoreal-web:latest}
    container_name: saldoreal_web
    build:
      context: .
      args:
        WHATSAPP_BOT_NUMBER: ${WHATSAPP_BOT_NUMBER}
        WHATSAPP_SUPPORT_NUMBER: ${WHATSAPP_SUPPORT_NUMBER}
    ports:
      # Porta 80 do host já está sendo usada pelo nginx (api) — evitamos conflito
      - "8081:80"
    networks:
      - saldoreal
    restart: unless-stopped

networks:
  saldoreal:
    name: saldoreal
    driver: bridge
